    name: Deploy Vite React App to yamin.com.au

    on:
      push:
        branches:
          - main # IMPORTANT: Confirm this is your primary branch (e.g., 'master' or 'main')

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18' # Use a stable Node.js version compatible with your React app

          - name: Install Dependencies
            run: npm install

          - name: Build Vite React App
            # Pass the API key as an environment variable during the build process
            run: VITE_OPENWEATHER_API_KEY=${{ secrets.VITE_OPENWEATHER_API_KEY }} npm run build
            env:
              VITE_OPENWEATHER_API_KEY: ${{ secrets.VITE_OPENWEATHER_API_KEY }}


          - name: Deploy to cPanel via FTP
            uses: SamKirkland/FTP-Deploy-Action@v4.3.4
            with:
              server: ${{ secrets.FTP_SERVER }} # This will be ftp.studioho.com.au
              username: ${{ secrets.FTP_USERNAME }} # Your FTP username (e.g., yamin_deploy)
              password: ${{ secrets.FTP_PASSWORD }} # Password for the FTP account
              local-dir: dist/ # The folder in your GitHub repo containing your built Vite app
              server-directory: "" # Deploy to the root of the FTP account (which is yamin.com.au's web root)
              protocol: ftps # Use FTPS for secure connection
              delete: true
    
